import 'dart:async';
import 'dart:developer';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:scan_qr/core/resources/export_resources.dart';
import 'package:share_plus/share_plus.dart';
import '../../../core/widgets/export_custom_widget.dart';
import '../../home/controller/home_controller.dart';
import '../model/qr_scan_model.dart';

class QrScanController extends GetxController {
  Barcode? barcode;
  StreamSubscription<Object?>? subscription;
  bool isSnackbarActive = false;
  bool isDialogDisplayed = false;
  late MobileScannerController controller;
  final SecureStorageService secureStorageService = SecureStorageService();
  WifiScanResult? qrScannedData;
  @override
  void onInit() {
    super.onInit();
    controller = MobileScannerController(
      autoStart: false,
      formats: [BarcodeFormat.all, BarcodeFormat.qrCode],
      facing: CameraFacing.back,
      detectionSpeed: DetectionSpeed.noDuplicates,
    );

    startScanner(handleBarcode);
  }

  resetScanner() {
    stopScanner();
    startScanner(handleBarcode);
  }

  Future<WifiScanResult?> handleBarcode(BarcodeCapture barcodes) async {
    barcode = barcodes.barcodes.firstOrNull;
    if (barcode == null || barcode!.displayValue == null) {
      return null;
    }

    try {
      log("Scanned data: ${barcode!.contactInfo.toString()}");
      final qrData = WifiScanResult.fromBarcode(barcode!);
      log(qrData.toJson().toString());

      if (qrData.wifi != null && qrData.wifi!.ssid != null && qrData.wifi!.ssid!.isNotEmpty) {
        await secureStorageService.saveWifiData([qrData.wifi!]);
        Get.find<HomeController>().fetchWifiHistory();

        stopScanner();
        return qrData;
      } else if (qrData.url != null) {
        await secureStorageService.saveUrlData([qrData.url!]);
        Get.find<HomeController>().fetchUrlHistory();
        stopScanner();

        return qrData;
      } else if (qrData.contactInfo != null) {
          await secureStorageService.saveContactInfoData([qrData.contactInfo!]);
        Get.find<HomeController>().fetchContactInfoHistory();
        stopScanner();
        return qrData;
      } else {
        return null;
      }
    } catch (e) {
      return null;
    }
  }

  void startScanner(Function(BarcodeCapture) onDetect) {
    if (qrScannedData != null) {
      qrScannedData = null;
      update();
    }
    controller.start();
    subscription = controller.barcodes.listen(onDetect);
  }

  stopScanner() async {
    subscription?.cancel();
    subscription = null;
    await controller.stop();

    return;
  }

  GlobalKey qrKey = GlobalKey();
  Future<void> shareQr(GlobalKey qrkey, {String? text}) async {
    final filePath = await shareQrFromBytes(qrkey);
    await shareFunction(
      text: text ?? 'Shared from ScanQR',
      subject: 'QR code generated by ScanQR',
      thummbnailPath: XFile(filePath),
      files: [XFile(filePath)],
    );
  }

  @override
  void dispose() {
    controller.dispose();
    stopScanner();
    super.dispose();
  }
}
