import 'dart:async';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:scan_qr/core/resources/export_resources.dart';
import 'package:scan_qr/features/scan/model/scan_code_result_model.dart';
import 'package:share_plus/share_plus.dart';
import '../../../../core/widgets/export_custom_widget.dart';
import '../../../home/controller/home_controller.dart';
import '../../model/scanned_value_to_map_model.dart';

class BarcodeScanController extends GetxController {
  Barcode? barcode;
  StreamSubscription<Object?>? subscription;
  bool isSnackbarActive = false;
  bool isDialogDisplayed = false;
  late MobileScannerController controller;
  final SecureStorageService secureStorageService = SecureStorageService();
  ScannedCodeResultModel? barcodeScannedData;

  Uint8List? imageBytes;
  @override
  void onInit() {
    super.onInit();
    controller = MobileScannerController(
      autoStart: false,
      formats: [
        BarcodeFormat.code128,
        BarcodeFormat.code39,
        BarcodeFormat.code93,
        BarcodeFormat.codabar,
        BarcodeFormat.dataMatrix,
        BarcodeFormat.ean13,
        BarcodeFormat.ean8,
        BarcodeFormat.itf,
        BarcodeFormat.upcA,
        BarcodeFormat.upcE,
        BarcodeFormat.pdf417,
        BarcodeFormat.aztec,
      ],
      facing: CameraFacing.back,
      detectionSpeed: DetectionSpeed.noDuplicates,
      returnImage: true,
    );

    startScanner(handleBarcode);
  }

  Future<void> resetScanner() async {
    barcodeScannedData = null;
    imageBytes = null;
    barcodeKey = GlobalKey();
    await stopScanner();
    startScanner(handleBarcode);
    update();
  }

  Future<ScannedCodeResultModel?> handleBarcode(BarcodeCapture barcodes) async {
    barcode = barcodes.barcodes.firstOrNull;
    if (barcode == null || barcode!.displayValue == null) {
      return null;
    }

    try {
      final scannedData = ScannedRawValueModel.fromBarcode(barcode!);
      final barcodeData = ScannedCodeResultModel(
        displayValue: scannedData.displayValue,
        rawValue: scannedData.rawValue,
        format: scannedData.format,
        type: scannedData.type,
        wifi: scannedData.wifi,
        url: scannedData.url,
        contactInfo: scannedData.contactInfo,
        email: scannedData.email,
        sms: scannedData.sms,
        phone: scannedData.phone,
        geo: scannedData.geo,
        calendarEvent: scannedData.calendarEvent,
        timestamp: DateTime.now(),
        isBarcode: true,
      );
      imageBytes = barcodes.image;

      await secureStorageService.saveScannedValue(barcodeData);
      Get.find<HomeController>().loadHistory();
      stopScanner();
      return barcodeData;
    } catch (e) {
      return null;
    }
  }

  void startScanner(Function(BarcodeCapture) onDetect) {
    controller.start();
    subscription = controller.barcodes.listen(onDetect);
  }

  stopScanner() async {
    subscription?.cancel();
    subscription = null;
    await controller.stop();

    return;
  }

  GlobalKey barcodeKey = GlobalKey();
  Future<void> shareQr(
    GlobalKey barcodeKey, {
    String? text,
    String? subject,
    String? title,
    String? url,
  }) async {
    final filePath = await shareScannedValueFromBytes(barcodeKey);
    await shareFunction(
      text: text ?? 'Shared from ScanQR',
      subject: subject ?? 'QR code generated by ScanQR',
      thummbnailPath: XFile(filePath),
      files: [XFile(filePath)],
      title: title,
      uri: url,
    );
  }

  @override
  void dispose() {
    controller.dispose();
    stopScanner();
    super.dispose();
  }
}
